ALTER TABLE users DROP CONSTRAINT IF EXISTS fk_users_role;
DROP TABLE IF EXISTS role_menus;
DROP TABLE IF EXISTS role_permissions;
DROP TABLE IF EXISTS menu_items;
DROP TABLE IF EXISTS permissions;
DROP TABLE IF EXISTS roles;
